In [1]:
import pandas as pd
from componergy.paths import FIGURES_DIR
def table(fig, name):
    p = FIGURES_DIR / fig / f'{fig}_{name}.csv'
    return pd.read_csv(p) if p.exists() else f'missing: {p.name}'
for f in ('figure_02', 'figure_04', 'figure_05', 'figure_06', 'figure_07'):
    print(f); display(table(f, 'amplification'))

figure_02

,Source,Trend,Units,Compound_effect,Additive_expectation,Amplification_contrast,SE,CI_lo,CI_hi,p_value,p_exact,p_hac,N_shifts,q_value
0,Fossil,quadratic,z,0.741621,1.237625,-0.496005,0.447918,-1.373907,0.381898,0.254469,0.317518,0.207751,273,0.547969
1,Hydro,quadratic,z,-0.777066,-1.440419,0.663353,0.456986,-0.232324,1.559030,0.131023,0.175182,0.042929,273,0.547969
2,Solar,quadratic,z,-0.046656,-0.038118,-0.008538,0.377285,-0.748002,0.730927,0.982365,0.992701,0.989828,273,0.982365
3,Wind,quadratic,z,0.204970,0.545221,-0.340251,0.444629,-1.211708,0.531205,0.433067,0.521898,0.520719,273,0.649601
4,Nuclear,quadratic,z,-0.402293,-0.579307,0.177014,0.465803,-0.735943,1.089971,0.714215,0.689781,0.648544,273,0.857058
5,Other Renewable,quadratic,z,0.251763,0.650894,-0.399132,0.389343,-1.162231,0.363968,0.273984,0.328467,0.393860,273,0.547969

figure_04

,Region,Trend,Units,Compound_effect,Additive_expectation,Amplification_contrast,SE,CI_lo,CI_hi,p_value,p_exact,p_hac,N_shifts,q_value
0,Central Coast,linear,z,-0.270310,-0.817982,0.547672,0.514123,-0.459990,1.555335,0.234243,0.335165,0.424819,181,0.515334
1,Mojave Desert,linear,z,0.847143,0.351479,0.495663,0.526933,-0.537107,1.528434,0.355013,0.351648,0.101944,181,0.557877
2,North Central,linear,z,0.646885,0.556994,0.089891,0.602347,-1.090687,1.270469,0.905095,0.895604,0.839837,181,0.905095
3,North Coast,linear,z,-0.383850,0.256564,-0.640414,0.544238,-1.707101,0.426272,0.221400,0.285714,0.138359,181,0.515334
4,Northeast,linear,z,0.260368,0.460148,-0.199780,0.496227,-1.172368,0.772808,0.654815,0.708791,0.731832,181,0.894743
5,Sacramento-Delta,linear,z,0.393013,-0.517290,0.910303,0.547569,-0.162912,1.983518,0.083974,0.109890,0.131081,181,0.515334
6,San Joaquin Valley,linear,z,0.230659,-0.458671,0.689330,0.472927,-0.237589,1.616249,0.129321,0.137363,0.121239,181,0.515334
7,Sierra,linear,z,0.144584,-0.055168,0.199752,0.557482,-0.892893,1.292397,0.732063,0.708791,0.600056,181,0.894743
8,Sonoran Desert,linear,z,0.952865,0.371953,0.580912,0.539385,-0.476263,1.638088,0.293620,0.269231,0.108571,181,0.538303
9,South Coast,linear,z,0.715343,0.628340,0.087004,0.567327,-1.024936,1.198944,0.855052,0.857143,0.853743,181,0.905095
10,Southern Interior,linear,z,0.732425,0.049798,0.682627,0.509447,-0.315871,1.681124,0.175375,0.181319,0.196806,181,0.515334

figure_05

,Sector,Trend,Units,Compound_effect,Additive_expectation,Amplification_contrast,SE,CI_lo,CI_hi,p_value,p_exact,p_hac,N_shifts,q_value
0,Residential,linear,z,0.513356,0.230333,0.283023,0.523449,-0.742917,1.308963,0.637007,0.571429,0.464702,181,0.891810
1,Commercial,linear,z,0.489486,-0.135651,0.625137,0.519864,-0.393778,1.644052,0.187002,0.214286,0.292998,181,0.654508
2,Industrial,linear,z,0.268457,0.252827,0.015630,0.522960,-1.009352,1.040613,0.946014,0.989011,0.975812,181,0.946014
3,Ag With Water Pump,linear,z,0.197265,-0.572027,0.769292,0.445163,-0.103213,1.641796,0.071633,0.082418,0.154820,181,0.501428
4,TCU,linear,z,-0.001615,-0.609929,0.608314,0.558443,-0.486214,1.702842,0.286249,0.236264,0.200779,181,0.667915
5,Mining,linear,z,-0.159585,-0.416266,0.256682,0.506863,-0.736751,1.250114,0.532080,0.670330,0.589998,181,0.891810
6,Streetlighting,linear,z,0.035488,-0.092940,0.128428,0.545576,-0.940881,1.197737,0.839186,0.785714,0.747488,181,0.946014

figure_06

,Metric,Trend,Units,Compound_effect,Additive_expectation,Amplification_contrast,SE,CI_lo,CI_hi,p_value,p_exact,p_hac,N_shifts,q_value
0,Imbalance,linear,z,0.695719,0.123474,0.572245,0.527556,-0.461746,1.606235,0.287076,0.252747,0.462645,181,0.287076

figure_07

,Region,Trend,Units,Compound_effect,Additive_expectation,Amplification_contrast,SE,CI_lo,CI_hi,p_value,p_exact,p_hac,N_shifts,q_value
0,Central Coast,linear,z,-0.270310,-0.817982,0.547672,0.514123,-0.459990,1.555335,0.234243,0.335165,0.424819,181,0.515334
1,Mojave Desert,linear,z,0.847143,0.351479,0.495663,0.526933,-0.537107,1.528434,0.355013,0.351648,0.101944,181,0.557877
2,North Central,linear,z,0.646885,0.556994,0.089891,0.602347,-1.090687,1.270469,0.905095,0.895604,0.839837,181,0.905095
3,North Coast,linear,z,-0.383850,0.256564,-0.640414,0.544238,-1.707101,0.426272,0.221400,0.285714,0.138359,181,0.515334
4,Northeast,linear,z,0.260368,0.460148,-0.199780,0.496227,-1.172368,0.772808,0.654815,0.708791,0.731832,181,0.894743
5,Sacramento-Delta,linear,z,0.393013,-0.517290,0.910303,0.547569,-0.162912,1.983518,0.083974,0.109890,0.131081,181,0.515334
6,San Joaquin Valley,linear,z,0.230659,-0.458671,0.689330,0.472927,-0.237589,1.616249,0.129321,0.137363,0.121239,181,0.515334
7,Sierra,linear,z,0.144584,-0.055168,0.199752,0.557482,-0.892893,1.292397,0.732063,0.708791,0.600056,181,0.894743
8,Sonoran Desert,linear,z,0.952865,0.371953,0.580912,0.539385,-0.476263,1.638088,0.293620,0.269231,0.108571,181,0.538303
9,South Coast,linear,z,0.715343,0.628340,0.087004,0.567327,-1.024936,1.198944,0.855052,0.857143,0.853743,181,0.905095
10,Southern Interior,linear,z,0.732425,0.049798,0.682627,0.509447,-0.315871,1.681124,0.175375,0.181319,0.196806,181,0.515334